# ==========================================
# Application Configuration
# ==========================================
spring.application.name=NOTICE-SERVICE
server.port=8089

# ==========================================
# Database Configuration
# ==========================================
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/dwellora_notice}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:your_local_password}

# ==========================================
# JPA / Hibernate Configuration
# ==========================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# ==========================================
# Eureka Service Discovery Configuration
# ==========================================
eureka.client.service-url.defaultZone=${EUREKA_SERVER_URL:http://localhost:8761/eureka/}
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.hostname=localhost
eureka.instance.prefer-ip-address=false
eureka.instance.instance-id=${spring.application.name}:${server.port}


# ==========================================
# Kafka Configuration
# ==========================================
spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

spring.datasource.hikari.pool-name=NoticeServiceHikariPool
spring.datasource.hikari.maximum-pool-size=3
spring.datasource.hikari.minimum-idle=1