# ==========================================
# Application Configuration
# ==========================================
spring.application.name=USER-SERVICE
server.port=8083

# ==========================================
# Database Configuration
# ==========================================
spring.datasource.url=jdbc:postgresql://localhost:5432/dwellora_user
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:your_local_password}

# ==========================================
# JPA / Hibernate Configuration
# ==========================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# ==========================================
# Eureka Service Discovery Configuration
# ==========================================
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.hostname=localhost
eureka.instance.prefer-ip-address=false
eureka.instance.instance-id=${spring.application.name}:${server.port}

jwt.secret=${JWT_SECRET:dwellora_super_secret_key_that_is_at_least_256_bits_long_for_hs256}
jwt.expiration=86400000

# ==========================================
# Kafka Configuration
# ==========================================
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=user-group
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer


spring.datasource.hikari.pool-name=UserServiceHikariPool
spring.datasource.hikari.maximum-pool-size=3
spring.datasource.hikari.minimum-idle=1